[package]
name = "calculator-wasm"
version = "0.1.0"
edition = "2024"

[dependencies]
meval = "0.2.0"
wasm-bindgen = "0.2.100"

[lib]
crate-type = ["cdylib", "rlib"]

[dev-dependencies]
wasm-bindgen-test = "0.3.34"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"